### PR TITLE
Add array Find method, docs, tests

### PR DESCRIPTION
**Pull request by jkvyff**
Unsure of which example type to use for overloading, so added second example in "src/arrays/find.d.ts".
prob can just use the simplest case, but let me know.

### CODE REVIEW

**Comment by jkvyff** [comment]
Ref: #40

**Comment by evanplaice** [comment]
Also, don't worry about adding typings `.d.ts`. They get automatically regenerated (ie `clean:typings` and `build:typings`) every time the version is bumped.

**Comment by evanplaice** [comment]
Props for taking this one on. The `thisArg` argument is a real pain.

**Comment by evanplaice** [comment]
My bad, having a second example in the JSDoc is good. It just won't be visible unless I get a chance later to patch DocDown so it'll output more than one example.

If you decide to add it back in, rename `@exmple2` -> `@example` to make it a valid JSDoc tag.

**Comment by jkvyff** [comment]
kk, ill add them back in.

**Pull request closed without merging**
