### PR TITLE
 add arrays.intersection

### PR DESCRIPTION
**Pull request by jkvyff**

### CODE REVIEW

**Comment by jkvyff** [comment]
Ref: #92

**Comment by evanplaice** [comment]
FYI, updating your local `master` copy then rebasing the feature branch on top of it works better than merging master into the feature branch.

**Comment by evanplaice** [comment]
The `master` branch is protected (ie blocks push -f) but you can force push onto feature branches if you need to clean up the history.

**Comment by evanplaice** [comment]
I think there is a more efficient approach. Take a look at the [arrays.frequency](https://github.com/vanillaes/absurdum/issues/56) spec.

Instead of creating sets for each array and doing a ton of lookups.

You can determine the intersections in 2 steps:
1. determine the frequency (ie how many arrays it appears in) for each item
2. filter the array of frequencies to extract only the values where `frequency = 3 of input arrays`

Does that make sense?

**Comment by jkvyff** [comment]
I don't know if it applies perfectly, as one would still need to search through each array for each unique element. I could optimize with a method more like 'some' that breaks off array search on find.

The function with the fastest real run time flips based on browser or device.
https://jsperf.com/reduce-intersection-benchmark/1

Let me know if I am missing something about the implementation.

```
function intersection (array, ...arrays) {
  const unique = [...new Set(array)]
  if (arguments.length === 1) return unique;
  return unique.reduce((acc, element) => {

    // if array includes element, then create or increment object frequency record
    const frequency = arrays.reduce((res, cur) => {
      if (cur.reduce((bool, elem) => {
        if (bool) return bool;
        if (elem === element) { return true; }
      }, false)) {
        res[element] = !res[element] ? 2 : ++res[element];
      }
      return res;
    }, {});

    // filter object for records with counts equal to number of inputs
    if (Object.values(frequency)[0] === arguments.length) {
      acc.push(Object.keys(frequency)[0])
    }
    return acc;
  }, []);
}
```

**Comment by evanplaice** [comment]
Nevermind. I thought it would be something more like.

```javascript
function intersection (...arrays) {
  const numArrays = arrays.length;
  return [...arrays
    .reduce((prev, curr) => prev.concat(curr))
    .reduce((acc, curr) => {
      if (acc.has(curr)) {
        acc.set(curr, acc.get(curr) + 1);
      } else {
        acc.set(curr, 1)
      }
      return acc;
    }, new Map())]
    .reduce((acc, curr) => {
      if (curr[1] === numArrays) { acc.push(curr[0]); }
      return acc;
    }, []);
} 
```

But failed to consider arrays that contain more the same value more than once.

I'm going to go ahead and land this as is.

**Comment by evanplaice** [comment]
OK, this works. I have no idea if it's faster than your solutions

```javascript
function intersection (...arrays) {
  const numArrays = arrays.length;
  return [...arrays
    .reduce((acc, curr) => {
      acc.push([...new Set(curr)]);
      return acc;
    }, [])
    .reduce((acc, curr) => acc.concat(curr))
    .reduce((acc, curr) => {
      if (acc.has(curr)) {
        acc.set(curr, acc.get(curr) + 1);
      } else {
        acc.set(curr, 1)
      }
      return acc;
    }, new Map())]
    .reduce((acc, curr) => {
      if (curr[1] === numArrays) { acc.push(curr[0]); }
      return acc;
    }, []);
} 
```

**Comment by jkvyff** [comment]
Pretty comparable in an initial test. They are both the fastest apparently.

image

**Pull request merged**
