### PR TITLE
camelCase method, tests, docs

### PR DESCRIPTION
**Pull request by jkvyff**
Ref: #165

### CODE REVIEW

**Comment by evanplaice** [comment]
`/(?<=[0-9])|[\u2019|\u002D|-|_|'|\s]+/` Huh?

Keep `\u002D`

ITT, `\u2019` is a 'smartquote'. Apple devices inserts these, which can unexpectedly break stuff. Lodash replaces them, it doesn't use them as a delimiter. Likewise, `'` single quotes shouldn't be a word delimiter either.

What's the number prefix match `(?<=[0-9])` for?

Maybe add `\u2014` for emdash. Apple devices replace `--` with these.

**Comment by evanplaice** [comment]
On an unrelated note. This lib may be starting to reach critical mass. The downloads surpassed jquery-csv for the 1st week of 2020 at almost 2.5K.

https://www.npmjs.com/package/absurdum

**Comment by jkvyff** [comment]
Will update based on the suggestions, Also:
- Lodash has the behavior that any letter after a number is treated as the beginning of a new word and so capitalized. So `(?<=[0-9])` is to delimit the space after a digit and make the next character capital.
- The `'` was put in while testing `\u2019` though should be removed.
- Any feedback on norms has been helpful as the deeper I delved, the more divided people seemed on what to keep or remove.

**Comment by evanplaice** [comment]
Cool. The number prefix pattern is interesting. Lets go with it.

- keep the unicode hyphen `\u002D`
- remove the smart quote `\u2019`
- remove the single quote `'`
- keep the number prefix `(?<=[0-9])`
- add the emdash `\u2014`

Unless I missed something or you think something should be added. LGTM :+1:

**Comment by jkvyff** [comment]
Not using `(?<=[0-9])` had a 10x speedup in a quick bench, don't know if that changes your mind haha.
- Checked test: With x 103,111 ops/sec ±0.60% (65 runs sampled)
- Checked test: Without x 995,717 ops/sec ±1.03% (66 runs sampled)

**Comment by evanplaice** [comment]
Oh... Umm. Lets leave it out.

I had a feeling RegEx backtracking could have bad perf but that's abysmal.

**Pull request merged**
