### PR TITLE
Array every, method, docs, tests

### PR DESCRIPTION
**Pull request by jkvyff**

### CODE REVIEW

**Comment by jkvyff** [comment]
Ref: #39

**Comment by evanplaice** [comment]
Would you mind rebasing this branch onto master? Otherwise this PR contains both the changes for `find` and `every`.

If you need help with this, don't hesitate to ask.

**Comment by jkvyff** [comment]
I didnt use a branch for find, but I will fix by reseting my master branch from yours, then building out the braches for each feature

**Comment by evanplaice** [comment]
So...

- create branches for each feature
- reset master to match the origin
- then rebase the feature branches onto master

**Comment by evanplaice** [comment]
On second thought, your master branch has been updated in parallel.

I suggest:
- backup your master branch by creating a `temp` branch from it
- create a new feature branch on the latest `master` commit
- cherry-pick the commits for the `arrays.find` feature

That could clear you of having to deal with any nasty conflicts

**Pull request closed without merging**
