### PR TITLE
add array zip method, docs, tests

### PR DESCRIPTION
**Pull request by jkvyff**
Ref: #4

### CODE REVIEW

**Comment by evanplaice** [comment]
Just a suggestion, you can simplify the branch logic (ie remove the ternaries) by giving `predicate` a default value.

```javascript
function zip (array1, array2, predicate=(a,b)=>[a,b]) {
```

**Comment by jkvyff** [comment]
Good call, much cleaner

**Comment by evanplaice** [comment]
LGTM, is there anything you want to add before I add this?

**Comment by jkvyff** [comment]
Nope, all good here

**Pull request merged**
