### PR TITLE
Arr some fixes for array mutation

### PR DESCRIPTION
**Pull request by jkvyff**

### CODE REVIEW

**Comment by evanplaice** [comment]
arrays.some was already merged in and released. It's probably best to cherry-pick the fix commit and push directly to master.

**Comment by evanplaice** [comment]
To push directly to this repo from your fork you need to do 2 things.

1. add this repo as a remote

```sh
git remote add upstream git@github.com:vanillaes/absurdum.git
```

2. push master to upstream

```sh
git push upstream master
```

-----

This works no differently than `git push origin master`. In fact if you want to quit pushing to your fork altogether you can set the url of your existing `origin` remote to this repo instead of your fork.

**Comment by jkvyff** [comment]
Can't push directly due to being protected . Error log included.
```remote: Resolving deltas: 100% (7/7), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "Verify" is expected.
To https://github.com/vanillaes/absurdum.git
 ! [remote rejected] master -> master (protected branch hook declined)

**Comment by evanplaice** [comment]
Sorry, this is a bit of a mess. I'll remove the protection.

Can you reset your master to match the origin, then cherry-pick 
bd18517 on top.

**Pull request closed without merging**
