### PR TITLE
obj-forIn method, tests, docs

### PR DESCRIPTION
**Pull request by jkvyff**
Ref: #144

### CODE REVIEW

**Comment by jkvyff** [comment]
2 comments on this one:

1. I didn't really know how to test this one with tape as part of its useful functionality comes with logging.

2. For object represented by the last param in the function, I used the object at the level of object the current property is being grabbed from. it seemed somewhat more useful as a way to dive through levels of prototyping. However, Lodash uses the original object, I don't know if I am missing a use case with that choice.

Any thoughts would be appreciated.

**Comment by evanplaice** [comment]
For 1.

Take a look at what I use here:
https://github.com/vanillaes/jqkill/blob/83f503e6e6045812d684f8309fe02a42425d8864/src/jqkill.spec.js#L24

Like all prototypes in JS, the console proto is mutable.

To intercept the console logging
- store the reference to the built-in method
- reassign it to use your own function
- restore it to the original when you're done

Some test tools abstract away the messy details but anything that requires a side effect (ex filesystem access) can be monkey patched like this for testing.

For 2, I'll take a look tomorrow when I'm in front of my laptop again.

**Comment by jkvyff** [comment]
fun trick, hadn't thought of that before.

**Comment by evanplaice** [comment]
Monkey patching allows for a lot of weird stuff. Like a filesystem mocking module where a directory structure is defined using JSON fixtures. The best part is, it's a universal solution; not tied to any particular testing framework.

As for the for-in, how hard would it be to add proto iteration. Can you concat the proto props + local props before running reduce on them? I'd prefer not to deviate from lodash on this since most users of this lib will likely come from lodash.

**Comment by evanplaice** [comment]
Maybe this'll work?

```javascript
const proto = Object.keys(TestObj.prototype);
const local = Object.keys(new TestObj());
const keys = new Set([...proto, ...local]);
```

Not sure if proto inheritance is a factor. Considering that multi-level inheritance is super uncommon in JS, lets skip it for now.

Also, this `proto` should default to an undefined prototype (ex when objects are created with `Object.create(null)`).

**Pull request merged**
